Merge cleaning & linting

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -5,8 +5,37 @@ on:
   pull_request:
 
 jobs:
+  clean:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Setup Bun
+        uses: oven-sh/setup-bun@v2
+
+      - name: Install dependencies
+        run: bun install
+
+      - name: Fix formatting
+        run: bun run format
+
+      - name: Fix linting issues
+        run: bun run lint:fix || true # Allow linting to fail, so we can commit the fixes
+
+      - uses: stefanzweifel/git-auto-commit-action@v6
+        id: auto-commit-action
+        with:
+          commit_message: "chore: fix formatting and linting issues"
+
   lint:
     runs-on: ubuntu-latest
+    needs: clean
 
     steps:
       - name: Checkout
